### POST-Anfrage
POST http://localhost:8080/expenses
Content-Type: application/json

{
  "name": "Kabel",
  "amount": "50",
  "person": "peter",
  "currency": "EUR"
}

### GET-Anfrage
GET http://localhost:8080/expenses/1
